import pytest
import polars as pl
from pymongo.errors import ConnectionFailure


